jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      extensions:
        - httpfs
        - parquet
    prod:
      type: duckdb
      path: 'jaffle_shop_prod.duckdb'
      extensions:
        - parquet
